import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const session = useSession();

  return (
    <>
      <Head>
        <title>Next T3 Stack Credentials Auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen px-5 py-8">
        <div>
          <h1>Click User Icon to login</h1>
        </div>
      </main>
    </>
  );
};

export default Home;
